sonar.projectKey=a37d247d999d45078578da95076815125dd07638
sonar.projectName=ERP-CITIZEN
sonar.projectVersion=6.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=src

# The value of the property must be the key of the language.
sonar.language=ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.ts.tslint.configPath=tslint.json
# if using local tslint then enable the line below
# sonar.ts.tslint.outputPath=reports/lint_issues.json


# Change the host.url to point to the 
# sonarcube server (default localhost)
sonar.host.url=http://localhost:9000